#!/bin/sh
# Copyright (C) 2020 Xue Liu <liuxuenetmail@gmail.com>

. $IPKG_INSTROOT/lib/functions.sh

config_load station

config_get reset_enable SX1301_conf enable_reset_pin

logger "sx1301 reset enable: $reset_enable"

if [ $reset_enable != "1" ]
then
    exit
fi

pio=pioE20

config_get pin SX1301_conf reset_pin

logger "sx1301 resetpin: $pin"

logger "sx1301 is resetting"

if [ -d "/sys/class/gpio/${pio}" ]
then
	echo 1 > /dev/null
else
	echo ${pin} > /sys/class/gpio/export
fi

echo "out" > /sys/class/gpio/${pio}/direction
echo "1" > /sys/class/gpio/${pio}/value
echo "0" > /sys/class/gpio/${pio}/value
echo "in" > /sys/class/gpio/${pio}/direction

logger "sx1301 is resetted"
